export const values = [
    {regio:"Brabant-Noord",regio_url:"brabant-noord",provincie:"Noord-Brabant",provincie_url:"noord-brabant"},
    {regio:"Friesland",regio_url:"friesland",provincie:"Friesland",provincie_url:"Friesland"},
    {regio:"Gooi en Vechtstreek",regio_url:"gooi-en-vechtstreek",provincie:"Noord-Holland",provincie_url:"noord-holland"},
    {regio:"Zuid-Holland Zuid",regio_url:"zuid-holland-zuid",provincie:"Zuid-Holland",provincie_url:"zuid-holland"},
    {regio:"Haaglanden",regio_url:"haaglanden",provincie:"Zuid-Holland",provincie_url:"zuid-holland"},
    {regio:"Zeeland",regio_url:"zeeland",provincie:"Zeeland",provincie_url:"zeeland"},
    {regio:"Noord en Oost-Gelderland",regio_url:"noord-en-oost-gelderland",provincie:"Gelderland",provincie_url:"gelderland"},
    {regio:"Utrecht",regio_url:"utrecht",provincie:"Utrecht",provincie_url:"utrecht"},
    {regio:"Drenthe",regio_url:"drenthe",provincie:"Drenthe",provincie_url:"drenthe"},
    {regio:"Groningen",regio_url:"groningen",provincie:"Groningen",provincie_url:"groningen"},
    {regio:"Noord-Holland Noord",regio_url:"noord-holland-noord",provincie:"Noord-Holland",provincie_url:"noord-holland"},
    {regio:"Twente",regio_url:"twente",provincie:"Overijssel",provincie_url:"overijssel"},
    {regio:"Amsterdam-Amstelland",regio_url:"amsterdam-amstelland",provincie:"Noord-Holland",provincie_url:"noord-holland"},
    {regio:"Gelderland-Zuid",regio_url:"gelderland-zuid",provincie:"Gelderland",provincie_url:"gelderland"},
    {regio:"Brabant-Zuidoost",regio_url:"brabant-zuidoost",provincie:"Noord-Brabant",provincie_url:"noord-brabant"},
    {regio:"Rotterdam-Rijnmond",regio_url:"rotterdam-rijnmond",provincie:"Zuid-Holland",provincie_url:"zuid-holland"},
    {regio:"Kennemerland",regio_url:"kennemerland",provincie:"Noord-Holland",provincie_url:"noord-holland"},
    {regio:"Midden- en West-Brabant",regio_url:"midden-en-west-brabant",provincie:"Noord-Brabant",provincie_url:"noord-brabant"},
    {regio:"Gelderland Midden",regio_url:"gelderland-midden",provincie:"Gelderland",provincie_url:"gelderland"},
    {regio:"Flevoland",regio_url:"flevoland",provincie:"Flevoland",provincie_url:"flevoland"},
    {regio:"Hollands Midden",regio_url:"hollands-midden",provincie:"Zuid-Holland",provincie_url:"zuid-holland"},

    {regio:"Limburg Noord",regio_url:"limburg-noord",provincie:"Limburg",provincie_url:"Limburg"},
    {regio:"Limburg Zuid",regio_url:"limburg-zuid",provincie:"Noord-Brabant",provincie_url:"noord-brabant"},
    {regio:"IJsselland",regio_url:"ijsselland",provincie:"Overijssel",provincie_url:"overijssel"},
    {regio:"Zaanstreek-Waterland",regio_url:"zaanstreek-waterland",provincie:"Noord-Holland",provincie_url:"noord-holland"},
    {regio:"Nederland",regio_url:"nederland",provincie:"Nederland",provincie_url:"Nederland"},
]